---
suse-12.0:
  repos:
    sles12-pool:
      name: "SLES12-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:GA/SLES/12/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    sles12-updates:
      name: "SLES12-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    sle12-ha-pool:
      name: "SLE12-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:GA/sle-ha/12/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    sle12-ha-updates:
      name: "SLE12-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    suse-enterprise-storage-2-pool:
      name: "SUSE-Enterprise-Storage-2-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:Update:Products:SES2/ses/2/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    suse-enterprise-storage-2-updates:
      name: "SUSE-Enterprise-Storage-2-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
