---
suse-12.1:
  aarch64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/aarch64",
              "obsproduct://build.suse.de/Devel:ARM:SLE-12-SP1:Update/SLES/12.1/POOL/aarch64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "c4a27581cec772c6dc641825d41c63d2"]
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/aarch64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
#       required: "mandatory"
      features: ["os"]
      repomd:
        tag: ["obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:aarch64/update",
              "obsproduct://build.suse.de/Devel:ARM:SLE-12-SP1:Update/SLES/12.1/POOL/aarch64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "c4a27581cec772c6dc641825d41c63d2"]
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/aarch64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
#      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Mitaka/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/aarch64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-7-pool:
      name: "SUSE-OpenStack-Cloud-7-Pool"
#      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/POOL/aarch64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/7/aarch64/product"
      ask_on_error: false
    suse-openstack-cloud-7-updates:
      name: "SUSE-OpenStack-Cloud-7-Updates"
#      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:7:aarch64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/7/aarch64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/aarch64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/aarch64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:aarch64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/aarch64/update"
      ask_on_error: false
    suse-enterprise-storage-3-pool:
      name: "SUSE-Enterprise-Storage-3-Pool"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:Update:Products:SES3/ses/3/POOL/aarch64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/Storage/3/aarch64/product"
      ask_on_error: false
    suse-enterprise-storage-3-updates:
      name: "SUSE-Enterprise-Storage-3-Updates"
      required: "optional"
      features: ["ceph"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2.1:aarch64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/Storage/3/aarch64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  x86_64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/x86_64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
#      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Mitaka/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/x86_64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-7-pool:
      name: "SUSE-OpenStack-Cloud-7-Pool"
#      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/POOL/x86_64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/7/x86_64/product"
      ask_on_error: false
    suse-openstack-cloud-7-updates:
      name: "SUSE-OpenStack-Cloud-7-Updates"
#      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:7:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/7/x86_64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/x86_64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-3-pool:
      name: "SUSE-Enterprise-Storage-3-Pool"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:Update:Products:SES3/ses/3/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/Storage/3/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-3-updates:
      name: "SUSE-Enterprise-Storage-3-Updates"
      required: "optional"
      features: ["ceph"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2.1:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/Storage/3/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  s390x:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/s390x"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/s390x/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:s390x/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/s390x/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/s390x"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
suse-12.2:
  aarch64:
    sles12-sp2-pool:
      name: "SLES12-SP2-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/SLES/12.2/POOL/aarch64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP2/aarch64/product"
      ask_on_error: false
    sles12-sp2-updates:
      name: "SLES12-SP2-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP2:aarch64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP2/aarch64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Mitaka/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/aarch64",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/aarch64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-7-pool:
      name: "SUSE-OpenStack-Cloud-7-Pool"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/POOL/aarch64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/7/aarch64/product"
      ask_on_error: false
    suse-openstack-cloud-7-updates:
      name: "SUSE-OpenStack-Cloud-7-Updates"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:7:aarch64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/7/aarch64/update"
      ask_on_error: false
    sle12-sp2-ha-pool:
      name: "SLE12-SP2-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/sle-ha/12.2/POOL/aarch64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP2/aarch64/product"
      ask_on_error: false
    sle12-sp2-ha-updates:
      name: "SLE12-SP2-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP2:aarch64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP2/aarch64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  x86_64:
    sles12-sp2-pool:
      name: "SLES12-SP2-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/SLES/12.2/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP2/x86_64/product"
      ask_on_error: false
    sles12-sp2-updates:
      name: "SLES12-SP2-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP2:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP2/x86_64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Mitaka/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/x86_64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-7-pool:
      name: "SUSE-OpenStack-Cloud-7-Pool"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/POOL/x86_64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/7/x86_64/product"
      ask_on_error: false
    suse-openstack-cloud-7-updates:
      name: "SUSE-OpenStack-Cloud-7-Updates"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:7:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/7/x86_64/update"
      ask_on_error: false
    sle12-sp2-ha-pool:
      name: "SLE12-SP2-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/sle-ha/12.2/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP2/x86_64/product"
      ask_on_error: false
    sle12-sp2-ha-updates:
      name: "SLE12-SP2-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP2:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP2/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  s390x:
    sles12-sp2-pool:
      name: "SLES12-SP2-Pool"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP2:GA/SLES/12.2/POOL/s390x"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP2/s390x/product"
      ask_on_error: false
    sles12-sp2-updates:
      name: "SLES12-SP2-Updates"
      required: "optional"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP2:s390x/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP2/s390x/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12-SP2:Update:Products:Cloud7/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7:Staging/suse-openstack-cloud/7/cd/s390x",
              "obsproduct://build.suse.de/Devel:Cloud:7/suse-openstack-cloud/7/cd/s390x"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
