---
suse-12.0:
  x86_64:
    sles12-pool:
      name: "SLES12-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:GA/SLES/12/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12/x86_64/product"
      ask_on_error: false
    sles12-updates:
      name: "SLES12-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12/x86_64/update"
      ask_on_error: false
    sle12-ha-pool:
      name: "SLE12-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:GA/sle-ha/12/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    sle12-ha-updates:
      name: "SLE12-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      ask_on_error: false
    suse-enterprise-storage-2-pool:
      name: "SUSE-Enterprise-Storage-2-Pool"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12:Update:Products:SES2/ses/2/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/products/storage/2/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-2-updates:
      name: "SUSE-Enterprise-Storage-2-Updates"
      required: "optional"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:2:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/Storage/2/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
suse-12.1:
  x86_64:
    sles12-sp1-pool:
      name: "SLES12-SP1-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/SLES/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP1/x86_64/product"
      ask_on_error: false
    sles12-sp1-updates:
      name: "SLES12-SP1-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update"
      ask_on_error: false
    cloud:
      name: "Cloud"
      required: "mandatory"
      features: ["openstack"]
      repomd:
        tag: ["obsproduct://build.suse.de/SUSE:SLE-12:SP1:Products:Cloud6/suse-openstack-cloud/6/POOL/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:6:Staging/suse-openstack-cloud/6/cd/x86_64",
              "obsproduct://build.suse.de/Devel:Cloud:6/suse-openstack-cloud/6/cd/x86_64"]
        key_md5: ["9a62177e1c6852d48453ed3909956d6b", "6e2920076653964b7de9d6d0421955bb"]
      url:
      ask_on_error: false
    suse-openstack-cloud-6-pool:
      name: "SUSE-OpenStack-Cloud-6-Pool"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsproduct://build.suse.de/SUSE:SLE-12:SP1:Products:Cloud6/suse-openstack-cloud/6/POOL/x86_64"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/OpenStack-Cloud/6/x86_64/product"
      ask_on_error: false
    suse-openstack-cloud-6-updates:
      name: "SUSE-OpenStack-Cloud-6-Updates"
      required: "mandatory"
      features: ["openstack"]
#      repomd:
#        tag: "obsrepository://build.suse.de/SUSE:Updates:OpenStack-Cloud:6:x86_64/update"
#        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/OpenStack-Cloud/6/x86_64/update"
      ask_on_error: false
    sle12-sp1-ha-pool:
      name: "SLE12-SP1-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP1:GA/sle-ha/12.1/POOL/x86_64"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP1/x86_64/product"
      ask_on_error: false
    sle12-sp1-ha-updates:
      name: "SLE12-SP1-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP1:x86_64/update"
        key_md5: "9a62177e1c6852d48453ed3909956d6b"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP1/x86_64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
